FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./

COPY frontend/package*.json frontend/
RUN npm run install-frontend

COPY backend/package*.json backend/
RUN npm run install-backend

COPY client/ client/
RUN npm run build --prefix frontend

COPY server/ server/

USER node

CMD [ "npm", "start", "--prefix", "backend" ]

EXPOSE 8000