name: ATALANTA Project CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        env:
            CI: true
            MONGO_URL: mongodb+srv://admin:Casa1992@cluster0.jiwerh0.mongodb.net/atalanta?retryWrites=true&w=majority
            MONGODB_URI: ${{secrets.MONGODB_URI}}
        strategy:
            matrix:
                node-version: [14.x, 16.x]
                mongodb-version: ['5.0', '6.0']
        runs-on: ubuntu-latest
        environment: DEV
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js version ${{ matrix.node-version }}0
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: MongoDB in GitHub Actions
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}
            - run: npm ci
            - run: npm ci --prefix backend
            - run: npm ci --prefix frontend
              env:
                  MONGODB_URI: ${{secrets.MONGODB_URI}}
                  PORT: 5000
                  JWT_SECRET: ${{secrets.JWT_SECRET}}
                  PAYPAL_CLIENT_ID: ${{secrets.PAYPAL_CLIENT_ID}}
                  RECAPTCHA_SITE_KEY: ${{secrets.RECAPTCHA_SITE_KEY}}
                  RECAPTCHA_SECRET_KEY: ${{secrets.RECAPTCHA_SECRET_KEY}}
                  CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
                  CLOUDINARY_KEY: ${{secrets.CLOUDINARY_KEY}}
                  CLOUDINARY_SECRET: ${{secrets.CLOUDINARY_SECRET}}
            - run: npm run build --prefix frontend
