name: ATALANTA Project CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        environment: DEV
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js version 16
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - run: npm ci
            - run: npm ci --prefix backend
            - run: npm start & npx wait-on http://localhost:5000 --prefix backend
              env:
                  MONGODB_URI: ${{secrets.MONGODB_URI}}
            - run: npm ci --prefix frontend
              env:
                  MONGODB_URI: ${{secrets.MONGODB_URI}}
                  PORT: 5000
                  JWT_SECRET: ${{secrets.JWT_SECRET}}
                  PAYPAL_CLIENT_ID: ${{secrets.PAYPAL_CLIENT_ID}}
                  RECAPTCHA_SITE_KEY: ${{secrets.RECAPTCHA_SITE_KEY}}
                  RECAPTCHA_SECRET_KEY: ${{secrets.RECAPTCHA_SECRET_KEY}}
                  CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
                  CLOUDINARY_KEY: ${{secrets.CLOUDINARY_KEY}}
                  CLOUDINARY_SECRET: ${{secrets.CLOUDINARY_SECRET}}
            - run: npm run build --prefix frontend
